name: Build and deploy frontend

on:
  push:
    paths:
      - classification_api/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./classification_api

      - name: Zip artifact
        run: |
          zip -r release.zip . -x ".venv/*" "__pycache__/*" "*.pyc" ".git/*"
        working-directory: ./classification_api

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app-frontend
          path: classification_api/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app-classification_api

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'cc-fund-classification-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_PUBLISHPROFILE_CLASSIFICATION_API }}
